### ISSUE TITLE
You commited your zsh_history you dumbass

### ISSUE THREAD

**Issue by sdegueldre** [Sim-frpt/.dotfiles#1]
https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

^ also useful for when you accidentally commit node_modules or a secret key.

**Comment by Sim-frpt** [comment]
:anguished:
I thought I had fixed that hahaha, I've started working on cleaning up this repo this morning and noticed your kindly worded issue :D Thanks :1st_place_medal:
